repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      args: [--py36-plus]

  - repo: local
    hooks:
      - id: types
        name: types
        entry: nox -s types --
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: nox -s lint --
        language: system
        types: [python]
        require_serial: true

  - repo: local
    hooks:
      - id: security
        name: security
        entry: nox -s security --
        language: system
        types: [python]
        require_serial: true